### PR TITLE
Update to Content Security Policy Post.

### PR DESCRIPTION
**Pull request by jpmedley**
Collaboration with original post author.

### CODE REVIEW

**Comment by jpmedley** [comment]
In case anyone is wondering, this content has already been reviewed by Mike West in Google Docs.

**Comment by PaulKinlan** [comment]
Wasn't wondering. Just didn't see the merge request coming in.

**Comment by jpmedley** [comment]
Thanks!

Joe Medley | Technical Writer | jmedley@google.com | 816-678-7195

**Comment by jpmedley** [comment]
Paul,

Do you know when the next push to prod is?

**Comment by PaulKinlan** [comment]
When I get around to it... it shouldn't be long.

**Pull request merged**
