### PR TITLE
Translated Best Practices for a Faster Web App with HTML5 in Korean

### PR DESCRIPTION
**Pull request by joshua1988**
The article is "Best Practices for a Faster Web App with HTML5" translated in Korean.

### CODE REVIEW

**Comment by joshua1988** [comment]
@PaulKinlan - Hi, Paul. Would it be okay for you to take a look at this pull request and merge it into the repository? I heard that you are in charge of building this repository! :)

**Comment by cwdoh** [comment]
LGTM. Really long time seeing translation PR on h5r. @joshua1988, you're certainly a hard-worker. :)

**Comment by joshua1988** [comment]
@cwdoh - Thanks for your support! :)

**Comment by PaulKinlan** [comment]
Thank you!

**Comment by joshua1988** [comment]
@PaulKinlan - Thanks a lot!

**Pull request merged**
