### PR TITLE
Fixes for imports article

### PR DESCRIPTION
**Pull request by ebidel**
R: @PaulKinlan

### CODE REVIEW

**Comment by ebidel** [comment]
cc @addyosmani @jeffposnick @gauntface

**Comment by PaulKinlan** [comment]
Will get live soon. We really should aim to get this in WF in the Kong term

**Comment by ebidel** [comment]
Like :crown: :monkey_face: ?!!?!?!

**Comment by ebidel** [comment]
Ping

**Comment by ebidel** [comment]
@PaulKinlan does this get auto pushed still?

**Pull request merged**
